[tools]
node = "24"
yarn = "1.22"

[tasks.server-dev]
dir = "server"
run = "docker compose up -d && yarn dev:setup && yarn dev"

[tasks.client-dev]
dir = "client"
run = "yarn dev"

[tasks.server-test]
dir = "server"
run = "docker compose up -d && yarn test && docker compose down"

[tasks.client-test]
dir = "client"
run = "yarn test"
