version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: circleci/mhb-primary:0.0.2
    working_directory: server
    steps:
      - checkout
      - run:
          name: Build
          command: sudo docker build -t oddgrd/myhomeboard:$CIRCLE_SHA1 .
      - run:
          name: Push
          command: sudo docker push oddgrd/myhomeboard:$CIRCLE_SHA1
      - run:
          name: Deploy
          command: |
            ssh root@164.90.209.133 
            docker pull oddgrd/myhomeboard:$CIRCLE_SHA1
            docker tag oddgrd/myhomeboard:$CIRCLE_SHA1 
            dokku/api:$CIRCLE_SHA1
            dokku deploy api $CIRCLE_SHA1
