version: 2.1

orbs:
  docker: circleci/docker@1.7.0

workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - docker/build:
        image: oddgrd/myhomeboard
        path: server
      - docker/push:
        image: oddgrd/myhomeboard
      - run:
        name: Deploy
        command: |
          ssh root@164.90.209.133 
          docker pull oddgrd/myhomeboard:$CIRCLE_SHA1
          docker tag oddgrd/myhomeboard:$CIRCLE_SHA1 
          dokku/api:$CIRCLE_SHA1
          dokku deploy api $CIRCLE_SHA1
