version: 2.1

orbs:
  docker: circleci/docker@1.7.0

workflows:
  test-deploy:
    jobs:
      - build
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push

jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - docker/build:
          image: oddgrd/myhomeboard
          path: server
  push:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - docker/push:
          image: oddgrd/myhomeboard
  deploy:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh root@164.90.209.133 
            docker pull oddgrd/myhomeboard:$CIRCLE_SHA1
            docker tag oddgrd/myhomeboard:$CIRCLE_SHA1 
            dokku/api:$CIRCLE_SHA1
            dokku deploy api $CIRCLE_SHA1
