---
name: 'deploy API'

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/deployAPI.yaml'
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/deployAPI.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./server

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: ./server/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Connect to Postgres service and run tests
        run: pnpm test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

  deploy:
    needs: test
    # Only deploy on push to master.
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@164.90.209.133:22/api'
          ssh_private_key: ${{ secrets.SSH_KEY }}
