---
name: 'testAndDeploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/testAndDeploy.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: server/yarn.lock
      - run: yarn
      - name: Connect to PSQL and run tests
        run: yarn test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # third-party action that cancels previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@164.90.209.133:22/api'
          ssh_private_key: ${{ secrets.SSH_KEY }}
